[package]
name = "solana_logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.6.1"

[features]
loglevel_debug = []
loglevel_info = []
loglevel_warn = []
loglevel_error = []